# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc4d9acfcdc3e2a8c8434dd315c3256dd279e6a56461c855929fd8502df560e765aca436e7789e44f56d9b13ced5e9f0bd5af3c2eb896611e46effe81620c39

test:
  secret_key_base: 81ad4ab3d8ef3a61293d6894ccea80f99041ada78a5294289ce2659e28fa32ed4834120b3b77901dbf7b001511be2f28178f588b72eae6047e11b7e0b8d123b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
